from turtle import *

# Click run to load the background of the program

# Replace 'pass' with the commands in your draw_base function
def draw_base():
    pendown()
    begin_fill()
    circle(10, 360, 4)
    end_fill()
    penup()
    seth(90)
    forward(15)
    seth(0)
    color("black")
def draw_home_plate():
    color("white")
    pendown()
    begin_fill()
    forward(30)
    right(90)
    forward(10)
    right(45)
    forward(20)
    right(90)
    forward(20)
    right(45)
    forward(10)
    end_fill()
    penup()
# Write the rest of your program below
speed(8)

color("white")
penup()
goto(90,-40)
right(90)
draw_base()
write("1st", align="left", font=("Arial", 12))
color("white")
goto(0, 50)
draw_base()
write("2nd", align="center", font=("Arial", 12))
color("white")
goto(-100,-50)
draw_base()
write("3rd", align="center", font=("Arial", 12))
goto(0, -55)
write("Pitcher", align="center", font=("Arial", 11))
goto(-15, -155)
draw_home_plate()
forward(5)
left(90)
forward(5)
seth(0)
color("black")
write("Home", align="left", font=("Arial", 11))
forward(150)
color("green")