from turtle import *

def half_body(color_choice_1, color_choice_2, color_choice_3, color_choice_4, radius):
    penup()
    color(color_choice_1)
    pendown()
    begin_fill()
    circle(radius)
    end_fill()
    penup()
    forward(radius*2)
    penup()
    color(color_choice_2)
    pendown()
    begin_fill()
    circle(radius)
    end_fill()
    penup()
    forward(radius*2)
    penup()
    color(color_choice_3)
    pendown()
    begin_fill()
    circle(radius)
    end_fill()
    penup()
    forward(radius*2)
    penup()
    color(color_choice_4)
    pendown()
    begin_fill()
    circle(radius)
    end_fill()
    penup()
    forward(radius*2)

penup()
goto(-140, 0)
for i in range(2):
    half_body("blue", "green", "yellow", "red", 20)