from turtle import *

shape("classic")
def draw_moon(moon_color, deg):
    color(moon_color)
    pendown()
    begin_fill()
    circle(30, deg)
    end_fill()
    
def draw_square(hed, rep, amt):
    seth(hed)
    for i in range(rep):
        forward(amt)
        right(90)

def draw_gib_cover(dir):
    for i in range(75):
        forward(1)
        dir(1.4)

def background():
    speed(0)
    penup()
    goto(0, 160)
    color("tan")
    write("The Lunar Cycle", font=("Futura", 35), align="center")
    goto(160, 135)
    write("(Note: Not To Scale)", font=("Futura", 8, "bold"), align="right")
    bgcolor("#0e31a1")
    penup()
    goto(-260, -100)
    color("gold")
    pendown()
    begin_fill()
    circle(100, 180)
    left(90)
    forward(200)
    end_fill()
    penup()
    goto(-185, 0)
    color("black")
    write("The", font=("Verdana", 8, "bold"), align="center")
    goto(-185, -15)
    write("Sun", font=("Verdana", 8, "bold"), align="center")
    goto(0, -50)
    seth(0)
    pendown()
    begin_fill()
    color("#37eb0e")
    circle(30)
    end_fill()
    penup()
    goto(0, -65)
    color("tan")
    write("The Earth", font=("Verdana", 8, "bold"), align="center")
    penup()
    goto(0, -80)
    color("#edeff5")
    pendown()
    pensize(3)
    circle(50, 345)
    seth(15)
    backward(10)
    forward(10)
    seth(280)
    backward(10)
    forward(10)
    pensize(1)
    
def lunarcycle(x, y):
    #New Moon
    speed(0)
    penup()
    goto(-110, -50)
    seth(0)
    draw_moon("grey", 360)
    penup()
    sety(-65)
    color("tan")
    write("New Moon", font=("Verdana", 8, "bold"), align="center")
    
    #Waxing Crescent
    penup()
    goto(-80, -130)
    draw_moon("#edeff5", 360)
    penup()
    goto(-130, -100)
    color("#0e31a1")
    seth(270)
    pendown()
    begin_fill()
    circle(30)
    end_fill()
    penup()
    goto(-80, -140)
    color("tan")
    write("Waxing Crescent", font=("Verdana", 8, "bold"), align="center")
    
    #First Quarter
    penup()
    goto(0, -165)
    seth(0)
    draw_moon("#edeff5", 180)
    penup()
    goto(0, -175)
    color("tan")
    write("First Quarter", font=("Verdana", 8, "bold"), align="center")
    
    #Waxing Gibbous
    penup()
    goto(80, -130)
    seth(0)
    draw_moon("#edeff5", 360)
    seth(135)
    color("#0e31a1")
    pendown()
    begin_fill()
    draw_gib_cover(right)
    seth(180)
    circle(50, 180)
    end_fill()
    penup()
    goto(90, -140)
    color("tan")
    write("Waxing Gibbous", font=("Verdana", 8, "bold"), align="center")
    
    #Full Moon
    penup()
    goto(110, -50)
    draw_moon("#edeff5", 360)
    penup()
    goto(115, -65)
    color("tan")
    write("Full Moon", font=("Verdana", 8, "bold"), align="center")
    
    #Waning Gibbous
    penup()
    goto(80, 20)
    draw_moon("#edeff5", 360)
    seth(45)
    color("#0e31a1")
    pendown()
    begin_fill()
    draw_gib_cover(left)
    color("#0e31a1")
    draw_square(0, 2, 20)
    draw_square(90, 4, 20)
    draw_square(0, 3, 20)
    draw_square(0, 3, 32)
    end_fill()
    penup()
    goto(125, 50)
    color("tan")
    write("Waning", font=("Verdana", 8, "bold"), align="center")
    goto(125, 35)
    write("Gibbous", font=("Verdana", 8, "bold"), align="center")
    
    #Third Quarter
    penup()
    goto(0, 120)
    seth(180)
    draw_moon("#edeff5", 180)
    penup()
    goto(-5, 50)
    color("tan")
    write("Third", font=("Verdana", 8, "bold"), align="center")
    goto(-5, 40)
    write("Quarter", font=("Verdana", 8, "bold"), align="center")
    
    #Waning Crescent
    penup()
    goto(-80, 20)
    draw_moon("#edeff5", 360)
    goto(-65, 20)
    color("#0e31a1")
    pendown()
    begin_fill()
    circle(30)
    end_fill()
    penup()
    goto(-60, 50)
    color("tan")
    write("Waning", font=("Verdana", 8, "bold"), align="center")
    goto(-60, 40)
    write("Crescent", font=("Verdana", 8, "bold"), align="center")
    hideturtle()
 
#Starts the actual execution of the code, the above are only the function definitions.   
user_name = input("What is your name?: ")
welcome_msg = "Hello {}, welcome to the depiction of the lunar cycle."
print(welcome_msg.format(user_name))
background()
canvas=getscreen()
clickmsg="Please click anywhere on the Canvas to reveal The Lunar Cycle!"
print(clickmsg)
canvas.onclick(lunarcycle)
done()